CREATE TABLE pilot
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name TEXT,
    last_name  TEXT,
    age        INTEGER NOT NULL,
    CONSTRAINT pk_pilot PRIMARY KEY (id)
);