ALTER TABLE aircraft
    ADD pilot_id BIGINT;

ALTER TABLE aircraft
    ADD CONSTRAINT FK_PILOTID_ON_AIRCRAFT FOREIGN KEY (pilot_id) REFERENCES pilot (id);

ALTER TABLE aircraft
    DROP COLUMN pilot;
